### ISSUE TITLE
Using cursorPaginate with orderBy and camelCased properties leads to errors.

### ISSUE THREAD

**Issue by benbjurstrom** [spatie/laravel-data#280]
Loving the Laravel data package. Really appreciate all the work you've put into it. 

One snag I ran into was using cursorPaginated collections with orderBy and camelCased properties. Given the following data object:

```php
use App\Models\User;
use Spatie\LaravelData\Data;

class UserData extends Data
{
    public function __construct(
        public string $id,
        public string $name,
        public string $createdAt,
    ) {
    }

    public static function fromModel(User $user): UserData
    {
        return new self(
            id: $user->id,
            name: $user->name,
            createdAt: $user->created_at,
        );
    }
}
```

I get
```bash
ErrorException : Undefined property: App\Data\UserData::$created_at` 
```

When using the cursor paginator like this:
```php
        $users = User::orderBy('created_at', 'DESC')->cursorPaginate(5);
        $userData = UserData::collection($users);

        // ErrorException : Undefined property: App\Data\UserData::$created_at
        $array = $userData->toArray();
```

Everything seems to work fine with paginate and simplePaginate. I reproduced the issue in a fresh Laravel install here: https://github.com/benbjurstrom/laravel-data-issue/blob/main/tests/Feature/ExampleTest.php

Let me know if you need any additional information. Thanks!

**Comment by Nir-An** [comment]
if the problem is between ``createdAt`` to ``created_at`` please try to use [mapping attributes ](https://spatie.be/docs/laravel-data/v2/as-a-data-transfer-object/creating-a-data-object#content-mapping-property-names)
also, you can check if  [content-paginated-collections](https://spatie.be/docs/laravel-data/v2/as-a-data-transfer-object/collections#content-paginated-collections) could be helpful for your needs.

**Comment by Nir-An** [comment]
the ``toArray`` ``toJson`` functions is like to "taking out" the object, so you need to use ``#[MapOutputName(SnakeCaseMapper::class)]``

```php
#[MapOutputName(SnakeCaseMapper::class)]
class UserData extends Data
{
    public function __construct(
        public string $id,
        public string $name,
        public string $createdAt,
    ) {
    }

    public static function fromModel(User $user): UserData
    {
        return new self(
            id: $user->id,
            name: $user->name,
            createdAt: $user->created_at,
        );
    }
}


```

**Comment by benbjurstrom** [comment]
> the `toArray` `toJson` functions is like to "taking out" the object, so you need to use `#[MapOutputName(SnakeCaseMapper::class)]`

Appreciate you trying to help but that doesn't fix it either. It seems to be looking for created_at specifically because it's in the orderBy clause.

**Comment by rubenvanassche** [comment]
Hi @benbjurstrom,

So the problem lies here: we map each item in the cursor collection into a data object so you can work with it. In the end we call toArray on the paginator and send this to the frontend. 

Cursor paginators need a property for the next query. The Laravel paginator looks for the created_at property but this does not exists anymore since the data object only knows createdAt. I guess you could pass in `['parameters' => ['createdAt']]` when creating the paginator as an option and this should probably take the correct parameter. Good luck!
