### ISSUE TITLE
Validation applied on the request

### ISSUE THREAD

**Issue by denjaland** [spatie/laravel-data#289]
Hi guys,

Doing some refactoring on our code base, using Laravel Data

Consider the following data object for creating a password reset request.
On our passwordreset we have a type; when a user creates a password reset from the controller, we want to have the type by default set to the default password reset type.

```php
class CreatePasswordResetData extends Data
{
    public function __construct(
        public readonly string $email,
        #[WithCast(EnumCast::class)]
        public readonly PasswordResetType $type,
    ) {
    }

    public static function rules()
    {
        return [
            'email' => 'required|email',
            'type' => 'required',
        ];
    }

    public static function fromRequest(Request $request): static
    {
        return new self(
            email: $request->input('email'),
            type: PasswordResetType::default()
        );
    }
}
```
So I created the fromRequest() function, which I believe would be used to create the Data object from a request.
Using injection in the controller, I then do:

```php
public function __invoke(CreatePasswordResetData $data, CreatePasswordResetAction $action) : void
    {
         $action($data);
    }
 ```
So in summary:
 - we have a Data object that we want to use in the controller, but also in other parts of the code
 - a valid Data object should always have the email address and the type, hence we validate both of them in the rules()
 - however when creating by the frontend using the controller, the type is not available, so we are using the fromRequest() method to add the default value for the type

It was my understanding that when injected into the controller __invoke method, the laravel-data would create the Data object using the fromRequest() method, _and apply validation rules on the result_ however, it seems that the validation rules are being applied onto the request (without the default value for type)... Is this expected behaviour, or is this actually a defect?

If it is expected behaviour, how can I then reuse these kinds of Data objects without having to duplicate them into two different models and still ensuring my Data object has all the properties that I expect?

**Comment by rubenvanassche** [comment]
We run a complete pipeline (so getting the data ready for building the data object) before we run the magic creation method when it has a request tyepd parameter. This to make sure the data you're working with is valid. So in this case we've validated the data before we ran the pipeline and thus a validation exception is thrown.

Take a look here: https://spatie.be/docs/laravel-data/v2/advanced-usage/pipeline

You can add extra properties before the pipeline, the problem is. That in the end we throw all this data away and just pass in the request because our pipeline generates an array of data and not a request. So you still would have to define the default in the magic creation method.

I'm not entirely sure if that's the best solution, since this is the second time someone runs into such a problem today. But if we don't run the pipeline somewhere on the request nothing would be validated and that's a bigger problem. 

A solution could be to run a minimal validation pipeline on the data object after creating it and then send out a validation exception if something goes wrong. But our complete validation logic has been built around the fact that no data object exists. Maybe that's something which needs to change in v3. But this opens also a lot of problems, what if we want to put an int into a data object property. This would crash completely. Stuff to think about ....
