### ISSUE TITLE
exclude, exclude_with rules not working

### ISSUE THREAD

**Issue by emilebourquin** [spatie/laravel-data#432]
Note: this is an oversimplification to show the issues I have been experiencing with _exclude_ , _exclude_with_, and other _exclude..._ rules in Data objects.

Given the form:

```
<form method="POST" action="/emailAddresses">
    @csrf
    Email: <input type="email" name="email" value="test1@example.com" /><br />
    MD5: <input type="text" name="email_md5" value="1234567890abcdef1234567890abcdef" /><br />
    <input type="submit" name="submit" value="Submit" />
</form>
```

the route:

```
Route::post('/emailAddresses', [EmailAddressController::class, 'store']);
```

the EmailAddressController store function:

```
public function store(EmailAddressData $emailAddressData)
{
    $theData = $emailAddressData->toArray();
    dd($theData);
}
```

the EmailAddressData DTO:

```
<?php
namespace App\Data;
use Spatie\LaravelData\Data;

class EmailAddressData extends Data
{
    public function __construct(
        public readonly ?string $email,
        public readonly ?string $email_md5,
    ) {}

    public static function rules()
    {
        return [
            'email' => ['email'],
            'email_md5' => ['exclude_with:email'],
        ];
    }
}
```

dd($theData); shows:

```
array:2 [▼ // app/Http/Controllers/EmailAddressController.php:42
  "email" => "test1@example.com"
  "email_md5" => "1234567890abcdef1234567890abcdef"
]
```

Note that email_md5 is not excluded. Even using the email_md5 rule as _exclude_ fails to exclude the email_md5 from the validated data.

However, using the exact same rules in a FormRequest does exclude the md5_email from the validated data:

```
public function store(StoreEmailAddressRequest $request)
{
    $theData = $request->validated();
    dd($theData);
}
```

```
<?php
namespace App\Http\Requests;
use Illuminate\Foundation\Http\FormRequest;

class StoreEmailAddressRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules()
    {
        return [
            'email' => ['email'],
            'email_md5' => ['exclude_with:email'],
        ];
    }
}
```

dd($theData) shows:

```
array:1 [▼ // app/Http/Controllers/EmailAddressController.php:42
  "email" => "test1@example.com"
]
```

**Comment by rubenvanassche** [comment]
This should be fixed with the next version!

**Comment by rubenvanassche** [comment]
We're going to revert this change, we have 2 issues currently:

- https://github.com/spatie/laravel-data/issues/439

At the moment validation works with both the mapped and non mapped names, but the mapped version name is always taken when present. We'll need to make some changes here to always use the data object property name. We'll do this in v4 because it's breaking stuff. At the moment the validator returns the mapped name but we need the non mapped version at this point to continue.

- https://github.com/spatie/laravel-data/issues/441

Also something we need to take a look at, v4 will be the best place for this.

This is the commit, it can easily be added locally for now: https://github.com/spatie/laravel-data/commit/afe0ac7a9d5ffcae11910bda26d0665467c799f2
