### ISSUE TITLE
validation fails for multi type or mixed type parameter without rules present

### ISSUE THREAD

**Issue by verner-lall** [spatie/laravel-data#457]
I'm using version 3.5.1

Having a minimal dto like this and running validateAndCreate returns validation errors for valid inputs
```php
class MinimalDto extends Data
{
    public function __construct(
        public null|int|array $input_id,
    ) {
    }
}
```

```php
MinimalDto::validateAndCreate(['input_id' => 1]); // The input id must be an array.

MinimalDto::validateAndCreate(['input_id' => [1]]); // The input id must be a number.

MinimalDto::validateAndCreate(['input_id' => null]); // ok
```

When null is not allowed, then can not be created at all.

Same happens with mixed type

```php
class MinimalDto extends Data
{
    public function __construct(
        public mixed $input_id,
    ) {
    }
}
```

```php
  "input_id" => array:3 [
    0 => "The input id must be a string."
    1 => "The input id field must be true or false."
    2 => "The input id must be an array."
  ]
```

I have a custom validator made to validate IntOrArrayOfInt.

When using the `#[Rule(new IntOrArrayOfInt)]` attribute, the same problem is present.

Currently the workaround is to add to the class the rules function, but for me that was not very intuitive and seems like a bug

```php
class MinimalDto extends Data
    {
    public function __construct(
        public null|int|array $input_id,
    ) {
    }

    public static function rules(): array
    {
        return [
            // for some reason can not use #[Rule(...)] attribute, still it tries to always enforce "array" AND "int"
            'input_id' => ['nullable', new IntOrArrayOfInt()],
        ];
    }
}    
```

**Comment by rubenvanassche** [comment]
Basically laravel-data and validating properties with multiple types (other than Lazy, Optional and null) is kinda a big no:

When we check the validation rules:

```php
MinimalDto::getValidationRules([])
```

We get:

```php
array:1 [ // /Users/ruben/Spatie/laravel-data/tests/DataTest.php:2402
  "input_id" => array:3 [
    0 => "nullable"
    1 => "numeric"
    2 => "array"
  ]
]
```

This looks correct at first sight, but Laravel validation can't handle this and if I'm not mistaken there is no other solution to fix this other than writing a custom validation rule and checking the properties for each type individually.

That's what you did if I'm not mistaken with `IntOrArrayOfInt`.

The reason why you cannot use the `Rule` attribute:

```php
class MinimalDto extends Data
{
    public function __construct(
        #[Rule(IntOrArrayOfInt::class)]
        public null|int|array $input_id,
    ) {
    }
}
```

If we look again at the generated rules:

```php
array:1 [ // /Users/ruben/Spatie/laravel-data/tests/DataTest.php:2405
  "input_id" => array:4 [
    0 => "nullable"
    1 => "numeric"
    2 => "array"
    3 => "Spatie\LaravelData\Tests\Fakes\Rules\ IntOrArrayOfInt"
  ]
]
```

We add that special rule but the inferred rules already exist so the validation still fails.

When using the rules method, you completely overwrite the rules inferred, so that's the reason why it is working. I'll add that to the docs to make it a bit more clear.

A simple solution is not possible, maybe we should add an attribute #[WithoutInferredRules] but then your data definition would look like this:

```php
class MinimalDto extends Data
{
    public function __construct(
        #[Rule(IntOrArrayOfInt::class), Nullable(), WithoutInferredRules]
        public null|int|array $input_id,
    ) {
    }
}
```

Which is also a lot to implement a simple rule. So, conclusion, you'll have to write a bit more.

**Comment by verner-lall** [comment]
Would it make more sense to not infer conflicting type rules from multi type variables, rather than infer all the rules?

**Comment by luckydonald** [comment]
I stumbled over this one as well, and just assumed laravel-data would be able to work with standard php typing.
It resulted in strange errors.

I feel it should recognise this cases and either:
- throw an error if there are incompatible types
- have a multi-type custom rule added automatically

@rubenvanassche can we reopen this?

**Comment by rubenvanassche** [comment]
For the multi types, I think it should be avoided. `$input_id` here for example. From the name I would suppose it is a single value, but it can also be an array? Which means if checks throughout your codebase always checking such a thing. Sending a normalized value from the frontend or making sure it is being normalized before entering the data object looks like the ideal solution to me.

> throw an error if there are incompatible types

Is this the role of the package? We can start checking everything, I think it is more of a task for the developer.

> have a multi-type custom rule added automatically

That's opening a can of worms, automatic validation rule generation is already a big PITA in this package. Adding such a feature would only complicate it more. Maybe something for version 5 or so but currently very low on my priority list.

> Also if I read that correctly, mentioned WithoutInferredRules class doesn't actually exist (yet), so that's not even solvable?

Always open to such a PR.
