### ISSUE TITLE
Request is validated before casts, impossible to submit '1,2' as float due to comma.

### ISSUE THREAD

**Issue by raveren** [spatie/laravel-data#478]
**↪️ To Reproduce**
There are quite a lot of different code files needed to reproduce this but based on my previous experience I feel like this issue might be put to the bin a.k.a. converted to discussion. However if you guys need it I will give you a reproduceable constellation: it consists of a controller which accepts a spatie data object as request object, route, and custom cast.

Here's what should give you enough info:

```php

class MyCustomRequest extends Data
{
    #[WithCast(CastNumericInputToFloat::class)] // takes string input and returns extracted `float` value
    public float $weight;
}


// test:

    public function test_stepOneStore(): void
    {
        $this->post(route('stepOneStore'), [
            'weight'           => '123,45', // users WILL submit comma-separated decimals here!
        ])->assertOk(); // Expected response status code [200] but received 302. "Weight must be numeric"
    }

```

**✅ Expected behavior**

The validated value should be post-cast, i.e. the float that was returned from `CastNumericInputToFloat` not the submitted string.

**🖥️ Versions**

All latest stable.

**Comment by luckydonald** [comment]
Isn't that like a locale issue?

**Comment by rubenvanassche** [comment]
At the moment such a thing is not possible:

- casts cannot create validation rules
- rule inferrers will always run and thus create the numeric rule

Something like this (#470) could maybe solve this. Since casts would be able to create their own rules in step one. In step two we could only generate nullable/optional rules and leave the numeric rule generation for what it is. The thing is, implementing that feature is a lot of work, so I'll hope to start soon working on this but it will take time.

As for now, why not overwrite the rules using a custom `rules` method? That's probably the solution, and why I'm closing this issue. It can be fixed, agreed there are better solutions to this but it will take weeks time before they can be implemented.

**Comment by onlime** [comment]
> As for now, why not overwrite the rules using a custom `rules` method? That's probably the solution, and why I'm closing this issue.

Hey @rubenvanassche thanks for the hint. That's a viable workaround, but please tell me what you meant by a custom `rules` method. Did you mean to introduce a dummy rule that always validates?
I am doing it just with the `#[WithoutValidation]` attribute, e.g. like this next to my custom casts:

```php
        #[WithoutValidation]
        #[WithCast(CsvCast::class)]
        #[WithTransformer(IdListTransformer::class)]
        public null|array|Optional $contactGroupIds,
```

The `#[WithoutValidation]` is basically needed everywhere where I cast some input type to another, or where I allow multiple different types as cast value.

**Comment by rubenvanassche** [comment]
Take a look at this section: https://spatie.be/docs/laravel-data/v3/as-a-data-transfer-object/request-to-data-object#content-rule-attribute after the first attributes.

The rules method always has precedence when generating rules over everything else.
