### ISSUE TITLE
ValidateAndCreate with nested data only accepts array, instead of data

### ISSUE THREAD

**Issue by Freeeon** [spatie/laravel-data#481]
**✏️ Describe the bug**
I have data with nested data. When I want to create nested data manually and send it to the parent ValidateAndCreate — i got error, that only accepts array for nested data. 

**↪️ To Reproduce**
```php

class ClientData extends Data
{
    public function __construct(
        public string          $name,
        public DocumentData    $document,
    ) {}
}

class DocumentData extends Data
{
    public function __construct(
        public string $type,
    ) {}
}

it('cannot validate nested data', function () {
    ClientData::validateAndCreate([
      'name' => 'Rick',
      'document' => new DocumentData('passport')
    ]);
});
```
```
Illuminate\Validation\ValidationException: The document must be an array. (and 1 more error)
/var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php:328
/var/www/html/vendor/laravel/framework/src/Illuminate/Validation/Validator.php:503
/var/www/html/vendor/spatie/laravel-data/src/Concerns/ValidateableData.php:30
/var/www/html/vendor/spatie/laravel-data/src/Concerns/ValidateableData.php:52
/var/www/html/tests/Feature/CreateClientTest.php:50
/var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:174
```

**✅ Expected behavior**
Created data with nested data

**🖥️ Versions**

Laravel: 10.13
Laravel Data: 3.6.0
PHP: 8.2.7

**Comment by rubenvanassche** [comment]
Hi @Freeeon,

At the moment validation is only for simple types (basically data from a request which gets validated into a data object). Though I would expect this case to work it actually won't because it expects an array version of the object. That's probably how you could solve it for now (calling `toArray` on it).

For in the future we need to make a few considerations:

- First of all, how to solve this. We expect an array but have an object, technically valid but it should be handled, this can only be done by directly looking at values and doing instanceof checks.
- Secondly what happens with the nested object, do we expect it already to be validated? Or should it also generate validation rules (probably), how to do this?

I'm gonna close this one for now, and add this as a not for our validation considerations in v4:  https://github.com/spatie/laravel-data/discussions/470
