### ISSUE TITLE
The After validation rule does not work in nested Data

### ISSUE THREAD

**Issue by Freeeon** [spatie/laravel-data#514]
**✏️ Describe the bug**
The After rule in data works correctly. But when I tried to use it in nested data, it was ignored

**↪️ To Reproduce**
```php

class ParentData extends Data
{
    public ChildData $data;
}

class ChildData extends Data
{
    public function __construct(
        #[Date]
        public string $issued_at,
        #[Date, After('issued_at')]
        public string $expire_at,
    ){}
}

class DateTest extends TestCase
{
    public function test_can_fail_dates()
    {
        $this->expectException(ValidationException::class);

        ChildData::validateAndCreate([
            'issued_at' => '2022-01-01',
            'expire_at' => '2021-01-01'
        ]);
    }

    public function test_can_fail_nested_dates()
    {
        $this->expectException(ValidationException::class);

        ParentData::validateAndCreate([
            'data' => [
                'issued_at' => '2022-01-01',
                'expire_at' => '2021-01-01'
            ]
        ]);
    }
}
```
```
There was 1 failure:

1) Tests\Feature\DateTest::test_can_fail_nested_dates
Failed asserting that exception of type "Illuminate\Validation\ValidationException" is thrown.
```

**✅ Expected behavior**
All tests must fail

**🖥️ Versions**

Laravel: v10.16.1
Laravel Data: v.3.7.0
PHP: 8.2.7

**Comment by oreillysean** [comment]
I attempted to fix the problem, but my attempted solution led to other failed test cases. This issue originates from variations in the 'issued_at' path.

So this works if issued_at is in the root

```php
class ChildData extends Data
{
    public function __construct(
        #[Date]
        public string $issued_at,
        #[Date, After('issued_at')]
        public string $expire_at,
    ){}
}
```

And this will work if issued_at is in a data ChildData

```php
class ChildData extends Data
{
    public function __construct(
        #[Date]
        public string $issued_at,
        #[Date, After('data.issued_at')]
        public string $expire_at,
    ){}
}
```
The crux of the problem lies within the [normalizeStringValidationAttribute](https://github.com/spatie/laravel-data/blob/90d43ee64d860390f838778dc9c5df2d1c01b157/src/Support/Validation/RuleDenormalizer.php#L52) method in the RuleDenormalizer class. A potential fix could be to automatically prepend the path, but this approach causes two existing tests to fail:

- it can reference the root validated object in nested data
- it will validate a collection with extra attributes

At present, I'm uncertain how to address this issue without negatively impacting backward compatibility. I wanted to share these findings in case they provide useful insights for a future resolution.

**Comment by rubenvanassche** [comment]
Check this: https://spatie.be/docs/laravel-data/v3/as-a-data-transfer-object/request-to-data-object#content-referencing-other-fields

```php
    class ChildData extends Data
    {
        public function __construct(
            #[Date]
            public string $issued_at,
            #[Date, After(new FieldReference('issued_at'))]
            public string $expire_at,
        ) {
        }
    }
```

Though I think we can PR a small bit where if we think it is a field reference the field reference is automatically used.

**Comment by rubenvanassche** [comment]
> Though I think we can PR a small bit where if we think it is a field reference the field reference is automatically used.

Hmm that's actually not possible, let's just update the docs
