### ISSUE TITLE
The SnakeCaseMapper and FromRouteParameter transformations do not work together in this case

### ISSUE THREAD

**Issue by ArcheeNic** [spatie/laravel-data#575]
**✏️ Describe the bug**
The SnakeCaseMapper and FromRouteParameter transformations do not work together in this case

**↪️ To Reproduce**

```php

#[MapName(SnakeCaseMapper::class)]
class AudioReviewRequest extends Data
{
    public function __construct(
        #[FromRouteParameter('lesson_id')]
        public int $lessonId,
        #[FromRouteParameter('child_id')]
        public int $childId,
        public UploadedFile $audioFile,
    ) {
    }


    /**
     * @return array<string, mixed>
     */
    public static function rules(ValidationContext $context): array
    {
        return [
            'audio_file' => [
                'required',
                'file',
                'mimetypes:' . implode(',', File::AUDIO_MIME_TYPES),
                'max:' . File::MAX_FILE_SIZE_MB * 1024,
            ]
        ];
    }
}
```
Returns a validation error that the lesson_id and child_id fields are required

**✅ Expected behavior**
I expect that the fields from the routes and the file from the request will be accepted

**🖥️ Versions**

Laravel: 9.41
Laravel Data: 3.9
PHP: 8.1

**Comment by rubenvanassche** [comment]
Hmm this is an interesting one, what's happening:

- We map property values, so audio_file gets mapped to audioFile
- We inject lesson_id as lessonId and child_id as childId
- Now we start generating validation rules these will be based upon a mapped input name if that exists and otherwise its real name.

Now here lies the problem, the package thinks lessonId and childId are in snake case and thus it will generate rules for `lesson_id` and `child_id`. So the validation fails.

The solution is the following:

- Keep track when mapping which properties were mapped
- Generate validation rules based upon the class property names
- When validation fails use the stored mapping from earlier to change the names of keys of the validation messages
- Update the validation error message bag with the new keys for the validation messages
- Throw the validation exception

We could start implementing this, the big problem is that we don't specify how custom rule names should be defined. At the moment you're free to use mapped names or the names of the properties. Too keep things simple to comprehend these rules should be defined with the property names which is breaking change.

Also this approach creates a few extra things to think about

1) Calling `getValidationRules` on a data object, should it use mapped property names or the original names when creating the rules?
2) Calling `validate` on a data object at the moment does not map properties but it might me required since we now always would generate rules based upon property names but it should be completely valid to provide a payload with mapped properties.

So, a lot of breaking stuff and things to think about. I was planning to fix this in v5 since we're going to change some things for better validation in that release. But it might be more useful to already implement this in v4.

As for v3, the problem can be solved by not setting the global mapper on a class but only set them for specific properties:

```php

it('bla', function () {
    class AudioReviewRequest extends Data
    {
        public function __construct(
            #[FromRouteParameter('lesson_id')]
            public int $lessonId,
            #[FromRouteParameter('child_id')]
            public int $childId,
            #[MapName(SnakeCaseMapper::class)]
            public string $audioReview,
        ) {
        }
    }

    Route::get('bla/{lesson_id}/{child_id}', function (Request $request) {
        dd(AudioReviewRequest::from($request));
    });

    handleValidationExceptions();
    withExceptionHandling();

    $this
        ->get('bla/1/2?audio_review=bla')
        ->dd();
});
```

I'm going to close this for now since there is a solution and we already have a plan to fix this in v4/v5.
