### ISSUE TITLE
Optional property should return null

### ISSUE THREAD

**Issue by ronssij** [spatie/laravel-data#601]
**✏️ Describe the bug**
Should an optional property return a null value instead of `Spatie\LaravelData\Optional::class` ?

**↪️ To Reproduce**
Provide us a pest test like this one which shows the problem:

on SectionData
```
public function __construct(
...
#[MimeTypes('image/*'), WithTransformer(MediaTransformer::class)]
public MediaData|Lazy|Optional|null $image,
...
) {}
```

on My controller.
```
public function update(SectionData $data, Section $section)
{
    return DB::transaction(function () use ($section, $data) {
        $section->update($data->all());

        if ($data->image) {
            // process image;
            dd($data->image);
        }

        return SectionData::from($section->load('image'));
    });
}
```

**✅ Expected behavior**
An optional field should required should return an empty or a null value.

**🖥️ Versions**

Laravel: 9.52.16
Laravel Data: ^3.9
PHP:  8.2.1

**Comment by rubenvanassche** [comment]
We had a fix for:

```php
$section->update($data->all());
```

Not including the value when it is optional, we had to revert that fix sadly enough due to the implementation being more difficult than expected. I saw a Pr somewhere that maybe fixes it but I need to get through it first.

As for this part:

```php
$data->image
```

This will always be Optional, since otherwise signatures like this aren't possible:

```php
public MediaData|Optional $image
```

You can always check for null and if not is it is an instance of Optional.

I'm gonna close this issue since we aren't going to change behavior around this. Feel free to add a comment to this.
