### ISSUE TITLE
Datacollection where method does not always work

### ISSUE THREAD

**Issue by rforced** [spatie/laravel-data#607]
**✏️ Describe the bug**

I have a property that is a data collection of Volumes. The volume object contains properties 'id' and 'stopped_at'.

`'volumes'   => DataCollection::class . ':' . Volume::class . ',default',`

```
App\Models\Volume {#7920
  +id: "asdff4324e.rsdf.234sdf23r",
  +stopped_at: null,
},
```

If I use where to find volumes where 'stopped_at' is null, I get the expected result.

```
$volumes->where('stopped_at', null);
= Spatie\LaravelData\DataCollection {#7937
    +items: [
      2 => App\Models\Volume {#8045
        +id: "asdff4324e.rsdf.234sdf23r",
        +stopped_at: null,
      },
    ],
  }
```

If I use where to find volumes by their id, I get an empty array. This is being manually tested in tinker to ensure I have the right IDs.

```
$volumes->where('id', "asdff4324e.rsdf.234sdf23r");
= Spatie\LaravelData\DataCollection {#8242
    +items: [],
  }
```

**🖥️ Versions**

Laravel: 10.32.0
Laravel Data: 3.9.2
PHP: 8.2.12

**Comment by rubenvanassche** [comment]
Interesting problem you've found! We provided all the parameters of the where to the Laravel where method but that one makes assumptions based upon the amount of parameters given. So since it expected 3 and we gave them three it expected the operator to be your id and not '='. Fixed in the next release.
