### ISSUE TITLE
Data casts store computed properties

### ISSUE THREAD

**Issue by ulcuber** [spatie/laravel-data#613]
**✏️ Describe the bug**

Data casts store computed properties

**↪️ To Reproduce**

```php
class Example extends Model
{
    protected $casts = [
        'config' => ConfigData::class,
    ];
}

class ConfigData extends Data
{
    #[Computed]
    public string $test;
}

$example->save()
```

**✅ Expected behavior**

Since computed properties contain derived data they should not be stored in database

---

New method to transform for storing to database instead of `toJson`:

(https://github.com/spatie/laravel-data/blob/39647b2d1affa196cd0f5ea05cfd649a16d2d11b/src/Support/EloquentCasts/DataEloquentCast.php#L73)

It could use `->toJson()` by default

aka `trait CastableData` in addition to `trait TransformableData`

---

Note this behavior in docs:
 
https://spatie.be/docs/laravel-data/v3/as-a-data-transfer-object/computed

https://spatie.be/docs/laravel-data/v3/advanced-usage/eloquent-casting

---

Skip computed properties like hidden:

https://github.com/spatie/laravel-data/blob/39647b2d1affa196cd0f5ea05cfd649a16d2d11b/src/Transformers/DataTransformer.php#L76

```php
if ($property->computed) {
    continue;
}
```

---

Or provide another workaround

**🖥️ Versions**

Laravel: v9.52.15
Laravel Data: 3.9.1
PHP: 8.1

**Comment by erikaraujo** [comment]
@rubenvanassche If we add `#[Hidden]`, wouldn't that also hide the computed property from when we do `->toArray()` or `->toJson()`?

Wouldn't it be better if, instead of throwing an error, the DTO just ignored the computed property being passed in to it? Maybe it should be a configuration option?

Throwing the exception adds no value to the DTO in my humble opinion.

**Comment by rubenvanassche** [comment]
But what's the reason behind the computed attribute then? Basically the only thing the attribute does is throwing this exception if a computed value is set.

**Comment by erikaraujo** [comment]
@rubenvanassche 

The reason behind the computed attribute is to compute. It will still compute whether we're throwing the exception or not according to this PR.

The only thing this PR does is silent the exception and re-compute the value if the value is being passed to the `Data` object. It's 100% optional, backwards compatible and I honestly see no reason for it not to be merged.

Currently, when I store `Data` on my database, it stores the computed properties too. They can't be hidden, because I need them in the front end.

When I'm trying to cast back the stored `Data` payload, it throws an exception instead of, well, just ignoring it and computing it again.

Alternatively, we could just not store computed properties in the Database - have them ignored as part of the casting - But I don't know this package well enough to implement that change myself - it would certainly be a much bigger change too.

Again - this change breaks no existing applications using this package and it's 100% optional. That would solve at least two developers problems - counting @ulcuber (realistic, many more). I honestly have no idea why this can't be merged.

It's a shame, really, because this change prevents me from upgrading this package and, therefore, upgrading to Laravel 11 without having to maintain a fork of it. :/

**Comment by rubenvanassche** [comment]
> The only thing this PR does is silent the exception and re-compute the value if the value is being passed to the Data object. It's 100% optional, backwards compatible and I honestly see no reason for it not to be merged.

Every path you split with extra config values makes flows within these kinds of packages if I can avoid that then I'll try to that.

> It's a shame, really, because this change prevents me from upgrading this package and, therefore, upgrading to Laravel 11 without having to maintain a fork of it. :/

Honestly, these kinds of reactions make it difficult for me to work on OSS, don't try to push us because you want to get something done fork the thing.

**Comment by erikaraujo** [comment]
> Honestly, these kinds of reactions make it difficult for me to work on OSS, don't try to push us because you want to get something done fork the thing.

I'm sorry - I do understand maintaining OSS isn't an easy task. I was just voicing my frustration for you to understand where I'm coming from too and why I need that change. Maybe I should've worded it a little differently.

**Comment by SimonMacIntyre** [comment]
> Currently, when I store Data on my database, it stores the computed properties too. They can't be hidden, because I need them in the front end.

This is my exact issue and use case. It took me longer than it should have trying to figure out this detail from documentation and sifting github issues. I assumed surely this was a bug. 

If you want to concat 2 properties as a computed string, storing both the individual strings and the concat, seems rather silly. 🤷 

In fact, removing the computed annotation works pretty much the same, since it just writes apparently any property to the database. Confusing behaviour indeed. The fact its stored really implies its not computed at all. 

Very confusing implementation all around. I understand being too busy to implement this, that's totally fair. But IMO this should remain an open issue because this current behaviour is very bizarre.
