### ISSUE TITLE
Wrong doc block

### ISSUE THREAD

**Issue by Temepest74** [spatie/laravel-data#668]
Laravel: latest
Laravel Data: latest
PHP: 8.1

It looks like if I do something like this: 
```
        $roles = RoleData::collect($user->roles);
```
and I hover over it I get `@var \Spatie\LaravelData\DataCollection<array-key, \App\Data\Models\RoleData> $roles`. Doing
```
        $roles = RoleData::collect($user->roles, Collection::class);
```
won't help either. to mention, if I do `dd($roles)` I get the correct type, being `\Illuminate\Database\Eloquent\Collection`. If it helps, I use ide-helper as well in my project

**Comment by rubenvanassche** [comment]
Our docblocks for `collect` use complex conditionals, so that PHPStan can correctly assume which type a call will provide. We even test these type, I guess the ide-helper cannot understand these conditional types and thus it will generate a wrong type.

As a fix, you could create your own data base class, extending ours and add you own collect method, calling ours but overwriting the method docblocks (if you're only using collections).
